### PR TITLE
String or character to be count

### PR DESCRIPTION
**Pull request by nikhil-chaurasia14**

### CODE REVIEW

**Comment by vindecodex** [comment]
@nikhil-chaurasia14 i added some comment on your source codes PR's, also created guide for PR's [CONTRIBUTE-GUIDE](https://github.com/vindecodex/counting-str/blob/master/CONTRIBUTE-GUIDE.md)

**Comment by nikhil-chaurasia14** [comment]
@vindecodex  The branch has been updated. I have added my details in the file package.json. Please review

**Comment by nikhil-chaurasia14** [comment]
Hey @vindecodex, I have updated the code as you said. Please review.

**Comment by nikhil-chaurasia14** [comment]
Hey @vindecodex, I have updated the code as you asked. Please review.

**Pull request merged**
