### PR TITLE
adding new line functionality

### PR DESCRIPTION
**Pull request by shubhdwiv12**

### CODE REVIEW

**Comment by shubhdwiv12** [comment]
i have added a new check functionality, kindly review @vindecodex

**Comment by shubhdwiv12** [comment]
@vindecodex  request you to review.

**Comment by shubhdwiv12** [comment]
Hi @vindecodex Is there any problem with the pull request, its been pending from long duration, request you to review and let me know if changes are needed.

**Comment by vindecodex** [comment]
> Hi @vindecodex Is there any problem with the pull request, its been pending from long duration, request you to review and let me know if changes are needed.

Have you created test for your functionality ?

**Pull request closed without merging**
